# 页眉设置
menu:
  首页: /
  归档: /archives

# 左侧栏带图标的链接
subnav:
  github: "https://github.com/Cat-eating-fish"
  # mail: "#"
  # rss: "/atom.xml"
  # zhihu: "#"
  # weibo: "#"
  # douban: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

# 设置 rss 为 false 以禁用订阅链接
# 留空 rss 以使用网站的订阅链接，并安装 hexo-generate-feed
# 如果你已经烧录过订阅源，请将 rss 设置为特定值
rss: /atom.xml

# 你可以将 excerpt_link 的值修改为你喜欢的任何内容
excerpt_link: 阅读全文
fancybox: true
mathjax: false

# 启用动画效果，推荐开启
animate: true

# 是否在新窗口中打开链接
open_in_new: false

favicon: /img/favicon.ico

# 你的头像 URL
avatar: /img/avatar.jpg

# 网易云音乐
music:
  enable: false
  # 网易云音乐上特定音乐的 ID
  id: 1334564681

# 如果需要启用 disqus，请将 'disqus_shortname' 设置为你的 disqus 用户名
# disqus_shortname:

# 是否启用标签云
tagcloud: true

# 是否启用 leancloud 统计访问量
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key

# 是否启用友情链接，如果不启用，设置 'friends' 为 false 且不要添加任何链接
friends:
  enable: true
  github: https://github.com/
# 关于你的简短介绍
aboutme: "不要迷恋哥，哥只是个传说。"
